[package]
name = "chess-erdos"
version = "0.1.0"
authors = ["Aleksei Zolotov <freopen@freopen.org>"]
edition = "2021"

[dependencies]
anyhow = "1.0.56"
bonsaidb = { version = "0.4.1", features = ["local"] }
chrono = { version = "0.4.19", features = ["serde"] }
futures = "0.3.21"
metrics = "0.18.1"
metrics-exporter-prometheus = "0.9.0"
opentelemetry = { version = "0.17.0", features = ["rt-tokio"] }
opentelemetry-otlp = "0.10.0"
pgn-reader = "0.20.0"
reqwest = "0.11.10"
serde = "1.0.136"
shakmaty = "0.21.0"
tokio = { version = "1.17.0", features = ["full"] }
tracing = "0.1.32"
tracing-opentelemetry = "0.17.2"
tracing-subscriber = { version = "0.3.11", features = ["env-filter", "json"] }
