[package]
name = "chess-erdos"
version = "0.1.0"
authors = ["Aleksei Zolotov <freopen@freopen.org>"]
edition = "2021"

[dependencies]
anyhow = "1.0.45"
chrono = { version = "0.4.19", features = ["serde"] }
env_logger = "0.9.0"
futures = "0.3.17"
log = "0.4.14"
pgn-reader = "0.19.0"
reqwest = { version = "0.11.4", default-features = false, features = [
  "rustls-tls",
] }
shakmaty = "0.20.2"
tokio = { version = "1.14.0", features = ["full"] }
