[package]
name = "chess-erdos"
version = "0.1.0"
authors = ["Aleksei Zolotov <freopen@freopen.org>"]
edition = "2021"

[dependencies]
anyhow = "1.0.45"
chrono = { version = "0.4.19", features = ["serde"] }
env_logger = "0.9.0"
futures = "0.3.17"
log = "0.4.14"
pbdb = "0.3.0"
pgn-reader = "0.19.0"
prost = "0.9.0"
prost-types = "0.9.0"
reqwest = "0.11.4"
shakmaty = "0.20.2"
tokio = { version = "1.14.0", features = ["full"] }
tonic = { version = "0.6.0", features = ["transport"] }
tonic-web = "0.2.0"

[build-dependencies]
pbdb = "0.3.0"
tonic-build = "0.6.0"
