[package]
name = "chess-erdos"
version = "0.1.0"
authors = ["Aleksei Zolotov <freopen@freopen.org>"]
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
bonsaidb = { version = "0.4.1", features = ["local"] }
chrono = { version = "0.4.19", features = ["serde"] }
console_error_panic_hook = "0.1.7"
dioxus = { version = "0.2.3", features = ["web"] }
dioxus-core = "0.2.0"
log = "0.4.16"
pot = "1.0.2"
serde = "1.0.136"
wasm-bindgen = "0.2.80"
wasm-logger = "0.2.0"

[target.'cfg(unix)'.dependencies]
anyhow = "1.0.56"
axum = "0.5.1"
futures = "0.3.21"
headers = "0.3.7"
include_dir = "0.7.2"
metrics = "0.18.1"
metrics-exporter-prometheus = "0.9.0"
metrics-util = "0.12.0"
mime_guess = "2.0.4"
opentelemetry = { version = "0.17.0", features = ["rt-tokio"] }
opentelemetry-otlp = "0.10.0"
pgn-reader = "0.20.0"
reqwest = "0.11.10"
shakmaty = "0.21.0"
tokio = { version = "1.17.0", features = ["full"] }
tracing = "0.1.32"
tracing-opentelemetry = "0.17.2"
tracing-subscriber = { version = "0.3.11", features = ["env-filter", "json"] }

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1

[package.metadata.wasm-pack.profile.dev.wasm-bindgen]
debug-js-glue = true
demangle-name-section = true
dwarf-debug-info = true
