[package]
name = "chess-erdos"
version = "0.1.0"
authors = ["Aleksei Zolotov <freopen@freopen.org>"]
edition = "2018"

[dependencies]
anyhow = "1.0.40"
bzip2 = "0.4.2"
chrono = "0.4.19"
env_logger = "0.8.3"
heed = { version = "0.11.0", default-features = false, features = ["mdbx"] }
lazy_static = "1.4.0"
log = "0.4.14"
parking_lot = "0.11.1"
pgn-reader = "0.18.0"
prost = "0.7.0"
prost-types = "0.7.0"
reqwest = { version = "0.11.3", default-features = false, features = ["blocking", "rustls-tls"] }
shakmaty = "0.19.0"
tokio = { version = "1.6.0", features = ["full"] }
tonic = "0.4.3"
tonic-types = "0.2.0"

[build-dependencies]
tonic-build = "0.4.2"
