[package]
name = "chess-erdos"
version = "0.1.0"
authors = ["Aleksei Zolotov <freopen@freopen.org>"]
edition = "2021"

[features]
dev = ["tonic-web"]

[dependencies]
anyhow = "1.0.49"
chrono = { version = "0.4.19", features = ["serde"] }
futures = "0.3.18"
metrics = "0.17.0"
metrics-exporter-prometheus = "0.6.1"
opentelemetry = { version = "0.16.0", features = ["rt-tokio"] }
opentelemetry-jaeger = { version = "0.15.0", features = ["rt-tokio"] }
pbdb = "0.3.0"
pgn-reader = "0.19.0"
prost = "0.9.0"
prost-types = "0.9.0"
reqwest = "0.11.6"
shakmaty = "0.20.2"
tokio = { version = "1.14.0", features = ["full"] }
tonic = { version = "0.6.1", features = ["transport", "tls"] }
tonic-web = { version = "0.2.0", optional = true }
tracing = "0.1.29"
tracing-opentelemetry = "0.16.0"
tracing-subscriber = { version = "0.3.2", features = ["env-filter", "json"] }

[build-dependencies]
pbdb = "0.3.0"
tonic-build = { version = "0.6.0" }
