---
- name: Install Chess Erdos backend
  hosts: server
  tasks:
    - name: Create chess_erdos user
      ansible.builtin.user:
        name: chess_erdos
        state: present
        home: /home/chess_erdos
    - name: Copy source to build directory
      ansible.builtin.copy:
        src: "target/release-server/chess-erdos"
        dest: "/home/chess_erdos/chess-erdos"
        owner: chess_erdos
        group: chess_erdos
        mode: 0755
    - name: Copy systemd unit file
      ansible.builtin.template:
        src: systemd.conf.j2
        dest: /etc/systemd/system/chess_erdos.service
        owner: root
        group: root
        mode: 0644
    - name: Enable and restart service
      ansible.builtin.systemd:
        name: chess_erdos
        state: restarted
        enabled: yes
        daemon_reload: yes
