[tasks.watch]
run_task = { name = ["build-dev"] }
watch = { watch = ["src/"] }

[tasks.build-dev]
run_task = { name = ["generate-dev", "move-to-generated"] }

[tasks.generate-dev]
run_task = { name = ["generate-wasm-dev", "generate-uno"], parallel = true }

[tasks.generate-wasm-dev]
command = "wasm-pack"
args = ["build", "--dev", "-d", "generated/wasm-building", "-t", "web"]

[tasks.generate-uno]
command = "pnpm"
args = [
    "unocss",
    "src/client/pages/*.rs",
    "src/client/components/*.rs",
    "--out-file",
    "generated/uno-building.css",
]

[tasks.move-to-generated]
script = '''
    rm -rf generated/wasm generated/uno.css
    mv generated/wasm-building generated/wasm
    mv generated/uno-building.css generated/uno.css
'''
